name: AutoPull
on:
  push:
  workflow_dispatch:
    branches:
      - auto_pull
  schedule: 
    - cron: "0 0 * * *"

jobs:
  auto-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update
        run: |
          git remote add upstream https://github.com/milklabdev/jetpack-compose-book.git
          git remote -v
          git config pull.rebase false
          git pull -f origin master:master –allow-unrelated-history
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
